fixed target pipeline

diff --git a/.devops/pay-wallet-code-review-pipelines.yml b/.devops/pay-wallet-code-review-pipelines.yml
--- a/.devops/pay-wallet-code-review-pipelines.yml
+++ b/.devops/pay-wallet-code-review-pipelines.yml
@@ -61,3 +61,96 @@ stages:
               summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
               reportDirectory: 'build/reports/jacoco/test/html'
             displayName: 'Publish Code Coverage on Azure Devops'
+
+  - stage: IntegrationTest
+    dependsOn: []
+    jobs:
+      - job: Integration_Test
+        steps:
+          - script: docker compose up -d
+            displayName: 'Run app with docker-compose'
+
+          - script: |
+              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
+            displayName: 'Health check pagopa-wallet-eventdispatcher'
+
+          - script: |
+              az storage message put \
+                --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localhost:10001/devstoreaccount1" \
+                --queue-name pagopa-wallet-cdc-queue \
+                --content '{
+                  "data":{
+                    "_id":"d283cbc5-cc48-4bc4-8f00-ddba4e24fc91",
+                    "walletId":"a527e843-9d1c-4531-ae5b-3809cc7abe7a",
+                    "auditWallet":{
+                      "paymentMethodId":"9d735400-9450-4f7e-9431-8c1e7fa2a339",
+                      "creationDate":"2024-10-16T15:03:18.541220633Z",
+                      "updateDate":"2024-10-16T15:03:36.447051359Z",
+                      "applications":[
+                        {
+                          "_id":"PAGOPA",
+                          "status":"ENABLED",
+                          "creationDate":"2024-10-16T15:03:18.378746985Z",
+                          "updateDate":"2024-10-16T15:03:18.378747385Z",
+                          "metadata":{}
+                        }
+                      ],
+                      "details":{
+                        "type":"PAYPAL",
+                        "pspId":"BCITITMM"
+                      },
+                      "status":"VALIDATED",
+                      "validationOperationId":"618534471407042909",
+                      "validationOperationResult":"EXECUTED",
+                      "validationOperationTimestamp":"2024-10-16T15:03:35.841Z"
+                    },
+                    "timestamp":"2024-10-16T15:03:36.527818530Z",
+                    "_class":"it.pagopa.wallet.audit.WalletOnboardCompletedEvent"
+                  },
+                  "tracingInfo":{}
+                }'
+            displayName: 'Write message to Azurite queue'
+
+          - script: |
+              sleep 2
+              eventFromKafka=$(kafka-console-consumer --bootstrap-server localhost:9092 --topic payment-wallet-injection-topic --from-beginning --timeout-ms 5000 --max-messages 1)
+              
+              expectedDataEvent='{
+                "data":{
+                  "_id":"d283cbc5-cc48-4bc4-8f00-ddba4e24fc91",
+                  "walletId":"a527e843-9d1c-4531-ae5b-3809cc7abe7a",
+                  "auditWallet":{
+                    "paymentMethodId":"9d735400-9450-4f7e-9431-8c1e7fa2a339",
+                    "creationDate":"2024-10-16T15:03:18.541220633Z",
+                    "updateDate":"2024-10-16T15:03:36.447051359Z",
+                    "applications":[
+                      {
+                        "_id":"PAGOPA",
+                        "status":"ENABLED",
+                        "creationDate":"2024-10-16T15:03:18.378746985Z",
+                        "updateDate":"2024-10-16T15:03:18.378747385Z",
+                        "metadata":{}
+                      }
+                    ],
+                    "details":{
+                      "type":"PAYPAL",
+                      "pspId":"BCITITMM"
+                    },
+                    "status":"VALIDATED",
+                    "validationOperationId":"618534471407042909",
+                    "validationOperationResult":"EXECUTED",
+                    "validationOperationTimestamp":"2024-10-16T15:03:35.841Z"
+                  },
+                  "timestamp":"2024-10-16T15:03:36.527818530Z",
+                  "_class":"it.pagopa.wallet.audit.WalletOnboardCompletedEvent"
+                },
+                "tracingInfo":{}
+              }'
+
+              if [ "$eventFromKafka" == "$expectedDataEvent" ]; then
+                echo "test passed successfully"
+              else
+                echo "fail! unexpected event"
+                exit 1   
+              fi
+            displayName: 'Validate message in Kafka topic'
